### ISSUE TITLE
Beatsync 0 does not set Beatsync Off

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#18]
(Derived from #16)

Wouldn't it be better to set Beatsync 0 but not Beatsync Off?
Since the following works as a Toggle, I think it would be better to operate there.

- Set Selected Sample Beatsync On/Off
- Set Selected Sample Beatsync On/Off 1 (Repitch)
- Set Selected Sample Beatsync On/Off 2 (Time-Stretch Percussion)
- Set Selected Sample Beatsync On/Off 3 (Time-Stretch Texture)

**Comment by esaruoho** [comment]
well, beatsync cannot be set to 0, it can only be set to 1. are you thinking that if i press -1 on a beatsync 1, it should not turn beatsync off, instead do nothing? (cos that's the only thing it can do, really, since 0 is not possible). @tkna91

**Comment by tkna91** [comment]
> it should not turn beatsync off, instead do nothing? (cos that's the only thing it can do, really, since 0 is not possible).

That is correct.

**Comment by esaruoho** [comment]
hi, sorry it's taken me so long to get on this. i think and i hope that tonight i'll be able to start scripting with this new machine and be able to take care of these.

**Comment by esaruoho** [comment]
ok, so i'm gonna close this, since i've now disabled the beatsync=off logic. i'll try and work on finding a method of posting a release of Paketti either via GitHub or by using the Tools website on Renoise. or send you a direct link. But let it be stated, that the change has been made. just not rolled into a xrnx yet.
