### ISSUE TITLE
Assign pitchbend to virtual keyboard pitchbend

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#19]
(Derived from #16)

ability to assign modulation pitchbend to virtual keyboard pitchbend.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/72a8ad5d-def0-4308-b94a-f98d2518cfde

**Comment by tkna91** [comment]
(Derived from #16)

Function to double/halve the Beatsync
The way the value transitions looks like it should be the same as the function below. (512 if an upper limit setting is needed)

- Double EditStep
- Halve EditStep

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/87e609ac-f483-493b-99d0-8a33a0c6b9e0)

screencast:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/bdc8011d-4e6d-446f-ad4a-2551916183b4

Form of value transition from 13:

- Double: 13, 26, 52, 104, 208, 416, 512
- Halve: 13, 6, 3, 1

**Comment by esaruoho** [comment]
i'm intrigued by this.

i can provide a very destructive selected_sample pitch = modified by <something> on midi, i.e. a midimapping for selected_sample_pitch, but it would not have much logic currently (i.e. if you have a sample at -24, and you want to pitchbend it +12 -12, it wouldn't go to -12 and -36, and then when you let go of the pitchbend, it wouldn't return back to -24). but depending on how you'd prefer it to go (selected instrument = all samples in the instrument are pitched up/down with +12 -12 control of pitchbend? or just selected_sample?), we can work this out.

what weirds me out about your video, is that you seem to be able to map the pitchbend directly to the pitch envelope for the instrument. but it seems you're not using the renoise pitchbend, instead an external pitchbend. 

also, can you confirm what happens if you don't have beatsync "on" and move the pitchbend set to the pitch? does it affect the audio? because afaik, beatsync = on _might_ actually mean that pitch-changing is disabled. if it's not right, please set me right.

I'd try this immediately (pitchbend) but i'm not currently in a place where i have access to a midipitchbend controller.

**Comment by tkna91** [comment]
The target is only selected_sample.

No MIDI controller is required, just a pitch bend controller (Modulation Set 01) from Renoise's standard GUI that can be assigned to the modulation's pitch input (Mixer: Pitch).

The pitch range seems to default to +12 -12, so it should be fine as is.

![image](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/20785144-f0a5-4212-b5d3-d7f3b0a1ed9a)

**Comment by tkna91** [comment]
Dragging does not move the initial mouse pointer, so you can play more comfortably than you might expect with just a mouse and keyboard.

screencast with audio:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/8d24ec2f-5b13-4799-9fa8-61188d2ef321

**Comment by tkna91** [comment]
> The target is only selected_sample.

No, it appears that the mapping is assigned to the entire selected instrument, not selected_sample.

**Comment by tkna91** [comment]
> also, can you confirm what happens if you don't have beatsync "on" and move the pitchbend set to the pitch? does it affect the audio? because afaik, beatsync = on might actually mean that pitch-changing is disabled. if it's not right, please set me right.

Time-stretching with Beatsync is useful for melodizing drums because the rhythm does not change, but even without them, the pitch bend here is the same as the effect because it only bends the pitch of the outputs.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/48db31d3-09a4-489e-ae6b-ff56bf152035

**Comment by esaruoho** [comment]
> ability to assign modulation pitchbend to virtual keyboard pitchbend.

hi, i'd like to pose some questions about this. like, would thsi be expected to generate a pitch-device for the selected_sample, and then after you stop the pitchbending, delete it, and then the next selected_sample would get the new pitch-device? i.e. do they need to be separate from eachother? would you record the pitchbend data to the pattern, or..?

or is the case "i wanna play a kickdrums, but use pitchbend <in any way> to detune / re-pitch it?"

do tell me more, if possible.

**Comment by tkna91** [comment]
Despite the very common use case of controlling pitch bend using the pitch bend control on a MIDI controller or Renoise's virtual MIDI keyboard, I still have to manually assign it every time in Renoise.
If anything, my essential desire may be to assign pitchbend to the pitchbend control by default when there is no pitchbend control assignment.
I have corrected this below, but it should be a control assignment for the entire current instrument, not per selected_sample.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/19#issuecomment-1913592863

If I do it manually, it looks like this
Screencast with Audio:.

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/0940114a-35b7-42c5-9a7a-bbb9574fdc15

Is it difficult to do a pitch bend assignment to a pitch bend control when there is no pitch bend control assignment, such as when the current instrument is changed?
If so, it can be done manually for the current instrument.

**Comment by esaruoho** [comment]
i have a sneaking suspicion that the only way to get this going is to actually save a XRNI (Renoise Instrument) inside Paketti and then load it. Hopefully it will have the settings set.
<img width="881" alt="Screenshot 2024-04-25 at 22 06 23" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/20489bec-66b2-4b86-aa15-1489dd9a1c62">

i was able to make the macros visible. the work on "binding a macro to pitch" has not been a trivial task and I'm still not sure if it is even possible.

**Comment by esaruoho** [comment]
@tkna91 ok here's my workaround.
I can save something called "pitchbendi.xrni" within Paketti. it is an instrument that only contains the virtual midikeyboard pitchbend bind to the Modulation->Pitch.  It contains no samples and no other settings. This could be considered the "Init Instrument"
How would you prefer I move forward with this? I can in theory populate every empty instrument box slot with this instrument, or provide a Renoise song template that has this. or..?

This destructive method seems to be the only way thus far to accomplish this, until the Renoise API gets more features.

But while we can use this hack, I'd prefer to be giving you a solution that helps you rather than is a clunky workaround (even though it's a clunky workaround).

i could make a shortcut that initializes the instrument to have autofade, oversampling, Sinc interpolation, and pitch bend control. when pitchbend is set to pitch, then every sample in that instrument will be pitched up & down.

how should we proceed?

**Comment by esaruoho** [comment]
> > The target is only selected_sample.
> 
> No, it appears that the mapping is assigned to the entire selected instrument, not selected_sample.

actually, what's going on is that the mapping is separate for each Mod Group
<img width="538" alt="Screenshot 2024-04-25 at 22 29 31" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/04ba24f1-13f0-4eb4-859e-82a7a6e7679f">

so if certain samples are in certain mod groups (there's already a shortcut for setting selected_sample to specific modgroup, if mod groups exist..
then they will have separate pitch controls. i can only experiment with this when i have audio, but please check for yourself.

set one sample to modgroup1, bind pitchbend to pitch of modgroup1
create modgroup2, set another sample to modgroup2, bind pitchbend to pitch of modgroup2

then see what happens if you pitchbend while modgroup2 is selected.. and what happens if you pitchbend while modgroup1 is selected.

**Comment by tkna91** [comment]
I see. Fundamentally, it would require adding functionality to the API, and it seems difficult to make it work in a straightforward manner.
As for alternatives, if you can implement them easily, I'm inclined to realize what the trade-offs are, but if it's going to be complicated, I might as well do nothing for now.

Related links:
- https://forum.renoise.com/t/the-api-wishlist-thread/29285/356
- https://forum.renoise.com/t/can-virtual-keyboard-pitchbend-macro-mapping-be-mapped-to-a-modulation-item/72069
- https://forum.renoise.com/t/what-is-this-stuff-for/72181/

**Comment by esaruoho** [comment]
@tkna91 yep, as you've dug up, i've requested such features to be added and asked around.

i'm gonna give you an experimental build. here's a little video of it - no audio.
https://www.loom.com/share/bfec2a69997d44cd9829a11f919d208a?sid=23ec3feb-d9a0-41b5-8d9b-5ba61d25d277

to recap:
<img width="334" alt="Screenshot 2024-04-26 at 12 12 13" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/3899048e-faa1-4003-b1cf-366778c4f4f7">
<img width="315" alt="Screenshot 2024-04-26 at 12 12 23" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/1c7323ba-670e-4802-ba77-58672b1ed5ab">
<img width="636" alt="Screenshot 2024-04-26 at 12 12 35" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/c2a42b97-6678-4949-b016-99adf6ab2445">


and the build is at
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15128112/org.lackluster.Paketti_V3.54.xrnx.zip)


now, please tell me what you think. and it turned out that it is possible to first init an instrument and then doubleclick and load a sample in.
if this is what would be good enough (i.e. "prepare an instrument box slot, then load samples = no manual mapping required") - then do let me know and we can close this ticket. if you need additional tweaks (i can provide you with 12st 24st 36st 48st 64st pitchbend instruments and you can pick them from a list (menu or shortcuts), or, a preference for it in the Paketti Preferences).. 

anyway, let's keep the ball rolling, and you let me know if this is going towards what you're after.

**Comment by esaruoho** [comment]
@tkna91 how does it work for you?

**Comment by tkna91** [comment]
> i can provide you with 12st 24st 36st 48st 64st pitchbend instruments and you can pick them from a list (menu or shortcuts), or, a preference for it in the Paketti Preferences

Interesting. I am interested in it.
It would be nice to have it in the shortcuts and Paketti Preferences (and menus).
I feel that the Instrument Name and Modulation Set Name should be something like “12st-Pitchbend” so that it can be identified even if it is abbreviated.

Screenshot:
![20240427-104140_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/6aa7067a-ae0b-43be-986c-0edcc40e52a8)

**Comment by esaruoho** [comment]
hi, unfortunately what happens is that if i press a note with a sample in 12st modgroup1 and 24st modgroup2 and have modgroup2 selected, pitchbend that affects +24 pitch in modgroup2 and +12 pitch in modgroup1 changes samples in modgroup1 and modgroup2. so it's not a "pick one". unless if we keep destructively changing that all the samples are in modgroup2 or in modgroup1. but the resolution of pitchbend gets a bit interesting. i'm at a loss as to what kind of a problem this would solve, and how it would solve it.
i.e. should one keep changing the modgroups by shortcuts, or set all samples to a specific modgroup by shortcuts, or..?

i'm inclined to think it'd be more sensible to set the Init Instrument PitchBend in the preferences, so there's a 12st, 24st, 36st, 48st, 64st, 96st, and the "default" pitchbend is set by preferences, but there are also shortcuts for 12-24-36-48-64-96 instruments. this way you can pick it up yourself. how's that?

**Comment by esaruoho** [comment]
if you have ideas as to how it would stay good and useful for you, please let me know. for now i'm creating 12 24 36 48 64 96 instruments and providing shortcuts for loading each, and then also set preferences for "init pitchbend preference loader" which will read from preferences. i'll do it in two steps. first the 12-96 instruments, then the preference.

**Comment by esaruoho** [comment]
<img width="219" alt="Screenshot 2024-04-27 at 11 58 29" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/9efba5c3-0f91-4cf1-830d-d87181d43603">

i have these files prepared now, but gotta work on making the loader and the preferences

**Comment by tkna91** [comment]
May I have that file?
I am interested in how it will work.

**Comment by esaruoho** [comment]
> May I have that file? I am interested in how it will work.

which file?

**Comment by tkna91** [comment]
`*st_Pichbend.xrni`

**Comment by esaruoho** [comment]
<img width="344" alt="Screenshot 2024-04-27 at 14 20 48" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/7b8faa2f-9c11-4b12-ae1e-b88f36e441a8">

i'm slowly putting stuff in here. i still need to test that it works, and then can make an experimental xrnx build for you

**Comment by esaruoho** [comment]
<img width="354" alt="Screenshot 2024-04-27 at 14 22 53" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/21e123bf-1b63-4bd5-bba1-8b603414bc76">
the 0st made no sense so i renamed it to 12st and removed the 0st screenshot

**Comment by esaruoho** [comment]
@tkna91 try this build
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15138017/org.lackluster.Paketti_V3.54.xrnx.zip)

the shortcuts are there only, i didn't get around to doing the menu entries yet

**Comment by tkna91** [comment]
This is fun.

Screencast with audio:

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/ed2f4fe9-3ba1-4ff8-87d1-37c7fe590bca

It may be better to use the same Modulation Set Name, e.g., `12st_Pitchbend` instead of `Set 01`.

![20240427-204820_screenshot](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/4c5bb2d8-dfb5-40b0-8d52-497ed9ef39c2)

**Comment by esaruoho** [comment]
and i forgot the 48st shortcut but added it to the main menu, instrument box and shortcut:
<img width="639" alt="Screenshot 2024-04-27 at 14 53 32" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/a10ae939-f241-4ef5-b200-7fba4f8d7c0d">

<img width="627" alt="Screenshot 2024-04-27 at 14 53 59" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/900784f7-ee55-4d3f-8650-fcb369373cd5">

<img width="348" alt="Screenshot 2024-04-27 at 14 54 26" src="https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/4966687/74b9e9d8-c5de-4683-aa21-91e3c0bb6326">


here's the minor fix
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15138104/org.lackluster.Paketti_V3.54.xrnx.zip)

please could you confirm if this is working the way you want it to. i.e. pitchbends are automatically set.

the preference is not yet there, as that will take some time for me to work out.

**Comment by esaruoho** [comment]
> It may be better to use the same Modulation Set Name, e.g., `12st_Pitchbend` instead of `Set 01`.

that was easy to do.
the modulation set name will only appear when you have a sample in the instrument. so until there is a sample, there is no name for mod - load a sample, you'll see the modgroup name.
[org.lackluster.Paketti_V3.54.xrnx.zip](https://github.com/esaruoho/org.lackluster.Paketti.xrnx/files/15138153/org.lackluster.Paketti_V3.54.xrnx.zip)

here's the minor fix.

now, what's your take, is this feature finished, or..?

**Comment by tkna91** [comment]
Confirmed. It appears to be working as desired.
Thanks!

**Comment by esaruoho** [comment]
@tkna91 awesome. thanks! i wasn't sure if this could be done but turns out there was a way.
