### ISSUE TITLE
Move note under cursor with the cursor - push notes below cursor down, pull notes below cursor up

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#261]
I’m looking for a effective key mapping to

move the note under the cursor together with the cusor
push the notes below the cursor down
pull the notes below the cursor up
I could not find such options in the standard keys / pattern editor settings.
Is this possible (without scripting)?

https://forum.renoise.com/t/quick-and-easy-node-editing-in-pattern-editor/72690

**Comment by tkna91** [comment]
The following functions are already available.
- push notes below cursor down: Insert
- pull notes below cursor up: Backspace

Therefore, is the function to move the note following the cursor?
If I move the cursor with notes to an area that already has notes, do I need to remember the original notes while overwriting them?
Otherwise, if I move the cursor over the notes, it will affect them.
