### ISSUE TITLE
Sample layer mute/unmute/solo

### ISSUE THREAD

**Issue by dmt-hub** [esaruoho/org.lackluster.Paketti.xrnx#278]
issue: when having many sample layers - i want to mute some layers in one go - tool with shortcuts to do this & 2 options of muting/unmuting/soloing

Option 1:

The tool creates a sample fx layer set to mute and adds the selected sample layer to that fx so it is muted.  also a solo mode for this tool - the selected sample layer is not muted, but all others are going to the muted fx sample layer. pressing shortcut again will unmute or unsolo it again (reverse action).

Option 2:

press shortcut and the sample layer volume goes to -inf db. solo mode: all other sample layer besides the selected one goes to -inf db. 
press shortcut again - to bring back the volume to its original state (unmute) (reverse action)

**Comment by esaruoho** [comment]
@dmt-hub i really like this idea. so this would basically create a Sample FX layer called "Mute" and put stuff there. but.. what i do wonder is, if there's stuff in the Mute, does it kick it out of it? and what happens if there's multiple Sample FX Layers that are already in use? i have bumped into people who have a multitude of sample fx groups in use. how to tackle that? i guess i could store them but i worry a bit about state refresh.

the other thing "sample layer volume" - do people tend to set those sample layers volumes? again, re-fetching the state might be difficult. if we all agree on -INF dB to 0dB then that's fine, but anything more customized, needs protection against being wrecked.

i can do the "destructive version" first and then can try to figure out how to do the rest.

**Comment by esaruoho** [comment]
i have to stress, this is a brilliant idea, i just wanna work it out so it doesn't come back and require multiple runs to make it less destructive :) 
maybe MVP is best to test the waters first. btw, if you have an example you can share via discord or here, let me know (multiple sample fx layers, multiple sample layer volumes set..)


you know, there might be some crazy XRNI inject method that could be used for storing the current value, so it's not just -INF dB <-> 0dB, but let's see

**Comment by esaruoho** [comment]
i'm told the shortcuts i made for switcharoo (all others to -INF, selected to 0dB) take care of this, so closing.
