### ISSUE TITLE
Single Sample Loader may not be necessary

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#40]
From #34 

Multiple Sample Loader appears to be usable as a Single Sample Loader

https://github.com/esaruoho/org.lackluster.Paketti.xrnx/assets/102382754/7cc37307-4e72-4839-babb-77ff4b483895

**Comment by tkna91** [comment]
Maybe we can make it look like this
- Single Instrument Loader
- Multi Instrument Loader

**Comment by esaruoho** [comment]
thanks for the idea. it does make sense to do it like this. the single instrument loader would be "selection to drumkit" and the multiple instrument loader would be 1 sample per 1 new instrument. once i get the drumkit loader working, i can rename them like this and differentiate.

my real aim is to get 0G01 Loader to work with this, so that if i pick for instance 150 samples with the multiple loader with 0G01 enabled, i have automatically created 150 new tracks, each playing one of the 150 samples with 0G01 added automatically.
