### ISSUE TITLE
Paketti Feature List

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#46]
this is blocked by #45

so there's a need for a Feature List. There's just too much stuff. It needs to be fully organized so that once I start breaking it into animated gifs and short video clips, it'll be possible to conceive / conceptualize what exactly does Paketti do.

**Comment by esaruoho** [comment]
fix all add_keybinding lines so that the full function + description is there

**Comment by esaruoho** [comment]
ok, add_keybinding, add_menu, add_mini have all been fixed so the titles are on the same row. this should help in mass-grabbing alla these

**Comment by esaruoho** [comment]
and the real trick is
`():add_` - find all those and you have a big old list.

**Comment by esaruoho** [comment]
i've done plenty of edits

**Comment by esaruoho** [comment]
there's currently about 848 add's (menu entry, keybinding, midimapping).
this'll be one helluva feature list.

**Comment by tkna91** [comment]
There are indeed a great many features.
It may be hard work, but it may be helpful for users to write such a brief description in a table in README.md.
It would be good to transcribe it to the Renoise Tool page as well at the time of release.

| Function name | Description | Note |
| ------------- | ----------- | ---- |
| 12st PitchBend Instrument Init | Initialize the instrument with the relevant pitchbend instrument and assign the pitchbend to the pitchbend of the virtual keyboard. This is an alternative solution since it is not possible to load modulation set presets using the API. | https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/19

```
| Function name | Description | Note |
| ------------- | ----------- | ---- |
| 12st PitchBend Instrument Init | Initialize the instrument with the relevant pitchbend instrument and assign the pitchbend to the pitchbend of the virtual keyboard. This is an alternative solution since it is not possible to load modulation set presets using the API. | https://github.com/esaruoho/org.lackluster.Paketti.xrnx/issues/19
```

**Comment by tkna91** [comment]
Even if you don't aim for perfection, just a rough write-up, to the extent possible, would be helpful to the user. Basically, they would just want to know what functions are available. If it's too much trouble, you could just write the reference links or keywords in the Note for now.

**Comment by esaruoho** [comment]
i like your idea, @tkna91 but it would also need to state the scope, i.e. is it global or sample editor specific.

that would help a lot, i think.

**Comment by esaruoho** [comment]
i've been working on some form of readme.md update, but i'm not sure i like it. it's on the github now

**Comment by esaruoho** [comment]
closing as someone else better equipped is working on it
