### ISSUE TITLE
Load samples onto the Pitchbend Instrument from the right-click menu in the “Samples” area of Renoise

### ISSUE THREAD

**Issue by tkna91** [esaruoho/org.lackluster.Paketti.xrnx#47]
From #39 

Pitchbend Single Instrument Sample Load:
1. In the "Samples" area of Renoise, select one or more samples and right-click
1. Select a menu similar to the following
   - Pitchbend Single Instrument Sample Load
1. Load a Pitchbend Instrument into a Single Slot
1. Load all selected samples in Single instrument

Pitchbend Multiple Instrument Sample Load:
1. In the "Samples" area of Renoise, select one or more samples and right-click
1. Select a menu similar to the following
   - Pitchbend Multiple Instrument Sample Load
1. Load a Pitchbend Instrument into Multiple Slots
1. Load all selected samples in Multiple instrument

**Comment by esaruoho** [comment]
@tkna91 unfortunately the Disk Browser does not offer API functionalities for providing "selected files in Disk Browser". otherwise i'd definitely work it out like this - i.e., provide the feature of "select files in disk browser -> run script -> load with pitchbend".
we need to petition for Disk Browser API features (like setting the Tab to Samples, then outputting the path that the user is in to API, then also selected files to API.

**Comment by esaruoho** [comment]
blocked by API - feature has been requested though, but closing for now. if there's ever an API update, i can then do this easily. i hope they do do it.
