### ISSUE TITLE
tris SliceStretcher "uneven slices"

### ISSUE THREAD

**Issue by esaruoho** [esaruoho/org.lackluster.Paketti.xrnx#49]
from Tris:

The source is here - first function in the file:  https://github.com/triss/org.tris.SliceStretcher.xrnx/blob/main/main.lua 

I do have to 
- round up the uneven slices to nearest line length... nothing complex going on...
- We make a ratio of the number of frames vs the beastsync amount on the source file and
- use that to calculate the beatsync length for each slice.

**Comment by icasiino** [comment]
Excellent, however, similar to the Karate Chop tool instead of the ratio being based on the beat sync length of the original file, it could be based on the pattern length of the pattern editor, or a user defined length. Thanks Tris for explaining it better.

Here is the link to the Karate Chop Tool 

https://github.com/chris-roerig/renoise-karate/releases/download/release-1-1-0/com.jugwine.karate.xrnx
